// src/components/sections/Hero.tsx
import { HERO_ALT, HERO_COPY } from "@/content/hero"
import { SofteningImage } from "@/components/ui/SofteningImage"
import { GoldCta } from "@/components/ui/GoldCta"
import { ParallaxLayer } from "@/components/ui/ParallaxLayer"
import { DURATION } from "@/lib/utils/motion"

/**
 * Seconds. How long the rocks take to retreat, and how long their softening
 * takes — the two are one move and must be given the same number or the blur
 * lands before the scale does.
 *
 * Longer than a standard entrance (`DURATION`) because the rocks are the
 * largest things on the page and travel the furthest: the same duration that
 * suits a line of copy reads as a lurch across a shelf of rock.
 */
const HERO_RETREAT = DURATION * 1.5

/**
 * Seconds. The tile arrives on top of the rocks' retreat rather than after it —
 * roughly a third of the way in, so the two overlap instead of queueing.
 */
const TILE_DELAY = HERO_RETREAT / 3

/**
 * S2 — Figma node `22:789`. The main parallax section.
 *
 * The design only exists at 1920 × 1040, and every layer in it is placed as a
 * percentage of that frame. Those percentages are only meaningful on a box with
 * roughly that ratio, so the artwork lives in its own "stage" element that
 * keeps a wide ratio at every width. Below `lg` the stage is a normal block and
 * the copy flows underneath it; from `lg` up the stage fills the section and the
 * copy is placed over it exactly as in Figma.
 *
 * Stacking follows the child order in Figma, which is deliberate: the headline
 * sits at the very bottom so the domino tile crosses in front of the word
 * "WITHOUT". Because every layer carries an explicit z-index, DOM order is free
 * to differ — it is chosen for the mobile flow instead.
 *
 * Depth comes from the blur baked into the design (DESIGN-TOKENS §5): the more
 * blurred a layer, the further away it reads, and the slower it travels.
 *
 * On load the composition assembles itself. Both rocks start at full size and
 * sharp, then shrink towards the corner they are anchored to — top-right for
 * the upper one, bottom-left for the lower — so their outer edge stays pinned
 * and they retreat inwards rather than drifting away from the frame, going
 * soft as they go. The tile arrives while that retreat is still under way, out
 * of focus at first and then settling into the design's own slight blur.
 *
 * `SofteningImage` does the focus changes without animating `filter`. The
 * entrance is a one-off; scroll parallax takes over afterwards.
 *
 * Three moving layers, which is the per-viewport ceiling (RULES §12).
 */
export function Hero() {
  return (
    // `54.17vw` IS the design's ratio — 1040/1920 — so at 1920 the section is
    // 1040px tall and every percentage inside it is Figma's own. The `max()`
    // puts a floor under it, because the ratio alone makes a narrower window
    // give a shorter hero (780px at 1440, 693px at 1280) while the things
    // stacked inside it do not shrink at all: the CTA is 72px and the two copy
    // rows ~132px whatever the width. The content stops fitting below ~1480px,
    // which is exactly where the button began overlapping "WITHOUT" — measured
    // at 7px of bite at 1440 and 26px at 1280. Each extra pixel of height buys
    // 0.56 of gap (the headline sits at 0.44H while the block hangs off the
    // bottom), so clearing it with a readable margin takes 840.
    //
    // Written as a height and NOT as `aspect-[1920/1040] min-h-[840px]`, which
    // was the first attempt and is a trap: `aspect-ratio` resolves in both
    // directions, so the floor fed back through the ratio and forced the
    // section 1551px WIDE — the entire page scrolled sideways at every width
    // below that (measured `scrollWidth` 1551 against a 1280 viewport). A
    // height cannot push the width around.
    <section className="from-hero-top to-hero-bottom relative isolate flex min-h-dvh flex-col overflow-hidden bg-linear-to-b lg:h-[max(840px,54.17vw)] lg:min-h-0">
      {/* The stage IS the coordinate space, at every width: `inset-0` means a
          layer's percentages are percentages of the section.

          From `lg` the section carries the design's own 1920 × 1040 ratio, so
          those percentages are Figma's, unaltered. Below `lg` the same box is
          portrait, and each layer carries a second set of numbers.

          A single scaled frame was tried first and is what produced the mess
          the phone showed: a 1920 × 1040 box is only ~210px tall on a 390px
          screen, so the whole composition compressed into a band under the
          navbar and left a dead grey void between the headline and the CTA —
          a quarter of the screen with nothing in it. Widening the frame to
          fill that height is not available either, because every layer is
          sized as a fraction of the frame: the tile grows at the same rate and
          swallows the headline it is meant to pass behind.

          So the phone gets its own arrangement of the same three layers, keeping
          the design's diagonal — rock upper-right, tile through the middle,
          rock lower-left — spread over the full height instead of stacked in
          one band. `overflow-hidden` on the section clips the rocks' overhang,
          so nothing widens the page. */}
      {/* `z-10` is what puts the artwork in front of the headline. Without it
          the stage is `z-auto`, which is NOT a stacking context — so its
          children do not compete with the headline as a group. Each layer's
          own z-index is then resolved against the section directly, and the
          headline, painted later in DOM order at the same effective level,
          wins on tie-break and covers the tile. Giving the stage a real
          z-index makes the whole group outrank `z-0`, and the tile crosses in
          front of "WITHOUT" as the Figma child order intends.

          It pairs with `isolate` on the section: that keeps these indices —
          and the CTA block's `z-60` — a private scale, so nothing here can
          outrank the navbar's `z-50` in the page's root context. */}
      <div className="absolute inset-0 z-10">
        {/* Rocks are the heaviest layers, and were once dropped below md to
            spare low-end phones the compositing. They are kept now because
            without them the phone layout is not the same design — three
            moving layers either way, which is the per-viewport ceiling
            (RULES §12).

            Upper-right on both, but far wider on a phone: a rock at Figma's
            45% of a portrait box is a small chip floating in grey, where at
            1920 the same fraction is a broad shelf. Sized to the viewport
            instead, it keeps the design's weight and its outer edge runs off
            the screen exactly as the design's runs off the frame. */}
        <ParallaxLayer
          speed={12}
          enter={{ scale: [1, 0.82], duration: HERO_RETREAT }}
          origin="topRight"
          anchor="top"
          decorative
          className="absolute top-[7%] left-[42%] z-10 w-[70%] lg:top-0 lg:left-[47.6%] lg:w-[45.4%]"
        >
          {/* `priority` even though the rock is decorative: it is the biggest
              thing painted above the fold, so Next measures it as the LCP
              element and warns that it loads lazily. Being decorative makes it
              MORE important to preload, not less — the entrance animation
              starts on mount whether or not the bitmap has arrived, so a lazy
              rock plays its 1.6s retreat as an empty box and pops in late. */}
          <SofteningImage
            src="/assets/global/decor-rock-top.png"
            alt=""
            width={888}
            height={361}
            priority
            from="0px"
            to="4px"
            duration={HERO_RETREAT}
          />
        </ParallaxLayer>

        {/* This one carries the phone layout. The gap between the headline and
            the CTA was the dead quarter of the screen; the lower rock is
            placed to run through it, so the eye travels headline → rock → CTA
            down the same left-leaning diagonal the design uses. `-left-[10%]`
            lets it bleed off the left edge rather than sit inside a margin. */}
        <ParallaxLayer
          speed={6}
          enter={{ scale: [1, 0.82], duration: HERO_RETREAT }}
          origin="bottomLeft"
          anchor="top"
          decorative
          className="absolute top-[43%] -left-[16%] z-20 w-[78%] lg:top-[62.5%] lg:left-[8.4%] lg:w-[49.2%]"
        >
          {/* Same reasoning as the upper rock — Next flagged this one as LCP
              too, since which of the two wins depends on the viewport. */}
          <SofteningImage
            src="/assets/global/decor-rock-bottom.png"
            alt=""
            width={970}
            height={403}
            priority
            from="0px"
            to="6.5px"
            duration={HERO_RETREAT}
          />
        </ParallaxLayer>

        {/* Height is pinned as well as width: Figma crops this one to a
            585 × 636 box (`objectFit: cover`). Letting the native 1882 × 2267
            ratio decide would make the tile a tenth taller than the design.

            The phone numbers are chosen against the headline, which wraps to
            two lines there where the design has one: the tile is held to 30%
            of the viewport — the share it takes at 1920 — and its bottom edge
            stops inside the first line, so it crosses "WITHOUT" and leaves the
            second line completely clear. Measured per line with
            `Range.getClientRects()`: 46–50% of line one, 0% of line two.

            Comes in while the rocks are still retreating — it starts around
            a third of the way into their 1.6s and lands before they settle,
            so the two overlap instead of queueing.

            It straightens as it arrives. The asset is drawn 26.3° off
            vertical already and Figma adds no rotation of its own, so `0` is
            the raw lean — it starts there and pulls back to the resting
            angle, which reads as the tile righting itself rather than
            switching on. It stops well short of upright; the slant is the
            design. */}
        <ParallaxLayer
          speed={24}
          enter={{
            opacity: [0, 1],
            scale: [0.8, 0.8],
            rotate: [-16, -6],
            duration: DURATION,
            delay: TILE_DELAY,
          }}
          anchor="top"
          className="absolute top-[16%] left-[43%] z-30 h-[15%] w-[30%] lg:top-[16.9%] lg:left-[35.3%] lg:h-[61.2%] lg:w-[30.5%]"
        >
          {/* The PNG, not the SVG next to it: that SVG is the very same
              1882 × 2267 raster wrapped in base64, so it buys no sharpness —
              it only costs 1.4 MB and, being an SVG, skips the optimiser
              entirely. `quality` is raised because the tile is the one image
              the eye actually lands on, and the default flattens its gold. */}
          <SofteningImage
            src="/assets/home/hero-domino-tile.png"
            alt={HERO_ALT.dominoTile}
            fill
            sizes="(max-width: 1024px) 30vw, 31vw"
            priority
            quality={90}
            from="10px"
            to="2px"
            duration={DURATION}
            delay={TILE_DELAY}
            imageClassName="object-contain"
          />
        </ParallaxLayer>

        {/* Grounds the composition into the page background. Figma specifies
            a circle, but at this box ratio its top corners are already opaque
            and leave a hard horizontal seam — a wide ellipse keeps the whole
            top edge transparent while the falloff still matches.

            `lg` only, and deliberately: it fades to `--color-bg`, which is the
            right colour where the design's own vignette sits. On a phone the
            section is still mid-gradient at its foot, so the same fade reads
            as a dark band — and nothing there needs grounding, because the
            rocks stop well short of the bottom edge. */}
        <div
          aria-hidden="true"
          className="absolute inset-x-0 bottom-0 z-40 hidden h-[36%] bg-[radial-gradient(ellipse_130%_100%_at_51%_0%,transparent_47%,var(--color-bg)_100%)] lg:block"
        />
      </div>

      {/* `mt-auto` here and on the CTA block below splits the leftover height
          between them, which lands the tagline/headline pair near the middle
          of the section — where `lg` puts it explicitly at 36%/44%. Pinning it
          under the navbar instead left the words at the top and the artwork
          orphaned below them.

          `pt-28` reserves the navbar's band. The navbar overlays the hero
          rather than occupying its own row, so without it `mt-auto` is free to
          centre the tagline right under the logo — the two then print on top
          of each other. The padding is part of the flex item, so it is counted
          before the leftover space is split. */}
      {/* The copy is deliberately still. The hero's entrance is the artwork
          assembling itself on load, and that is the whole of it — the words are
          what the moving pieces resolve into, so they are already in place when
          the rocks start to retreat.

          A scroll-triggered `Reveal` was tried here and taken back out: this
          section is on screen at load, so a scroll entrance either fires
          immediately (adding a second, competing entrance to the one the layers
          already play) or waits for a scroll that has nothing left to reveal. */}
      <p className="font-sans relative z-50 mt-auto pt-28 bg-linear-to-r from-white via-[var(--color-silver-mid)] to-white bg-clip-text px-5 text-center text-base font-semibold tracking-[0.24em] text-transparent uppercase lg:absolute lg:inset-x-0 lg:top-[36%] lg:mt-0 lg:pt-0 lg:text-2xl">
        {HERO_COPY.tagline}
      </p>

      {/* z-0 — behind every image, per the Figma child order. */}
      <h1 className="font-display relative z-0 mt-3 bg-linear-to-r from-white via-[var(--color-silver-mid)] to-white bg-clip-text px-5 text-center text-[length:var(--text-display-lg)] leading-none text-transparent uppercase lg:absolute lg:inset-x-0 lg:top-[44%] lg:mt-0">
        {HERO_COPY.headline}
      </h1>

      {/* Anchored to the bottom (`mt-auto`), so both the gap and the bottom
          padding push the CTA upwards. Figma leaves 63px between the button
          and the mission copy, and 107px below the last element.

          At `lg` those two are written as `vw`, not as the raw px. The section's
          height is pinned to its width by `aspect-[1920/1040]`, so it shrinks as
          the window narrows — but fixed padding does not, and the block ends up
          claiming a larger and larger share of a smaller and smaller hero.
          Measured: 373px tall at every width, which is 36% of the hero at 1920
          but 48% at 1440, where it had climbed 51px into the headline.

          3.33vw and 5.6vw are Figma's own 64 and 108 divided by 1920, so the
          design width still renders the design's numbers exactly, and every
          narrower one keeps the same proportion instead of the same pixels. */}
      <div className="relative z-60 mt-auto flex flex-col gap-10 px-5 pt-12 pb-10 md:px-10 lg:gap-[3.33vw] lg:px-20 lg:pt-0 lg:pb-[5.6vw]">
        {/* 340 × 72 in Figma (`31:1117`); the height is set by the component.
            `max-w-70` on a phone, not the full 340: at 390px wide the design's
            width fills 87% of the screen, where at 1920 the same button takes
            18% — so carrying the raw number across turns a compact capsule
            into a bar spanning the viewport. The pill radius is a fixed 48px,
            which caps how wide it can go before the capsule reads as a rounded
            rectangle. From `sm` the screen is wide enough for Figma's own
            340. */}
        <GoldCta href="#" className="mx-auto w-full max-w-70 sm:max-w-85">
          {HERO_COPY.primaryCta}
        </GoldCta>

        {/* Figma sets the two copy blocks against opposite edges. That reads as
            a pair only while they sit side by side; stacked on a phone, one
            ragged-left and one ragged-right block just looks misaligned — so
            below `lg` both centre, and the CTA stretches to the column. */}
        <div className="flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between">
          {/* Figma's own 432px block, narrowed between `menu` and `menu-lg`.
              That is exactly the band where the countdown card has been pulled
              up into this row: the card is a fixed 498px and centred, so the
              space on each side is `(vw − 498) / 2 − 80` of gutter, which at
              1400 is 371px against a 432px block. 288px clears it; from
              `menu-lg` the row is wide enough for the design's own width. */}
          <p className="font-sans max-w-108 text-center text-base leading-[26px] text-white lg:text-left lg:text-lg menu:max-w-72 menu-lg:max-w-108">
            {HERO_COPY.mission}
          </p>

          <div className="flex flex-col gap-4 lg:items-end">
            <p className="font-sans max-w-79 text-center text-base leading-[26px] text-white lg:text-right lg:text-lg">
              {HERO_COPY.accountability}
            </p>
            <a
              href="#"
              className="rounded-btn font-display focus-visible:ring-gold flex items-center justify-center bg-white/20 px-5 py-4 text-[length:var(--text-display-btn)] leading-none text-white uppercase focus-visible:ring-2 focus-visible:outline-none lg:w-73"
            >
              {HERO_COPY.secondaryCta}
            </a>
          </div>
        </div>
      </div>
    </section>
  )
}

// app/components/members/Hero.vue
<script setup lang="ts">
import { getMembershipStats } from "~/lib/api/client"
import { MEMBERS_COPY } from "~/content/members"

/**
 * The members hero — Figma node `401:19063`, 1920 × 1080 full bleed.
 *
 * This page does NOT open on the header band the other inner pages share. It
 * opens on a centred title over a gradient with a gold pill under it and four
 * figures across the foot, and that is the design's call rather than an
 * oversight to correct: the band is for pages that are documents or archives,
 * and this one is a pitch (D64).
 *
 * The title is not run through `SharpeningHeadline` for the same reason — Figma
 * gives it no `blur(7.5px)` start (`401:19069`), unlike every header-band title
 * in the file. Nothing to clear from, so nothing clears.
 *
 * **The vertical rhythm is measured, not flowed.** Figma positions all four
 * pieces absolutely — content at y:214, pill at 604, figures at 805 — and an
 * evenly-gapped column does not reproduce that: it centres everything and the
 * glow ends up behind the wrong element. The gaps below are the design's own
 * distances written as `vw` against the 1920 canvas, so the block is exact at
 * the design width and stays proportional either side of it.
 */
/**
 * The one fade both globe layers wear, and the reason it is a constant.
 *
 * The halo and the sphere draw the same edge from two different elements — the
 * halo the light outside it, the sphere the lit limb itself. If their masks
 * differ by so much as a stop, one dies before the other and the join between
 * them opens up: at the sides the rim was still burning after its glow had gone,
 * which reads as light leaking out of a seam. Written once, bound to both, so
 * they cannot drift apart.
 *
 * Anchored at the crown and falling off horizontally, and its radius is a
 * CUSTOM PROPERTY because the right value is not one number.
 *
 * The fade is measured against the sphere's box, but what has to be faded by is
 * the edge of the WINDOW — and the window covers a different share of the box at
 * every breakpoint, because a narrow screen needs a bigger circle to get a flat
 * horizon out of it. At 1920 the frame reaches ±37% of the box; at 768 it is
 * ±29%; on a 390 phone only ±21%. A single 44% radius is spent by the frame's
 * edge on desktop and barely started on a phone, which is exactly what happened:
 * the arc ran off both sides of the phone at full brightness.
 *
 * So each breakpoint sets `--edge-r` to roughly its own reach divided by 0.85 —
 * the fade is ~85% spent where the window ends, whatever the window is.
 */
const EDGE_FADE = `radial-gradient(
  ellipse var(--edge-r) 130% at 50% 0%,
  #000 0%,
  #000 18%,
  rgba(0, 0, 0, 0.62) 48%,
  rgba(0, 0, 0, 0.22) 72%,
  rgba(0, 0, 0, 0.05) 88%,
  transparent 100%
)`

/** How far round the sphere the light survives, by height. Shared for the same
 *  reason `EDGE_FADE` is. */
const LIMB_FADE = `linear-gradient(
  180deg,
  #000 0%,
  #000 10%,
  rgba(0, 0, 0, 0.6) 20%,
  rgba(0, 0, 0, 0.25) 31%,
  transparent 44%
)`

const haloStyle = {
  background: `radial-gradient(
    circle closest-side at 50% 50%,
    rgba(255, 248, 205, 0) 0%,
    rgba(255, 248, 205, 0) 84.6%,
    rgba(255, 248, 205, 0.741) 87.2%,
    rgba(252, 232, 178, 0.51) 88.2%,
    rgba(247, 218, 152, 0.317) 89.2%,
    rgba(242, 205, 133, 0.18) 90.2%,
    rgba(238, 196, 120, 0.128) 91.2%,
    rgba(232, 188, 110, 0.056) 93.2%,
    rgba(228, 182, 104, 0.017) 95.2%,
    rgba(228, 182, 104, 0) 97.2%
  )`,
  maskImage: `${LIMB_FADE}, ${EDGE_FADE}`,
  WebkitMaskImage: `${LIMB_FADE}, ${EDGE_FADE}`,
  maskComposite: "intersect",
  WebkitMaskComposite: "source-in",
}

/**
 * The sphere's limb, measured off `decor-hero-globe.png` down the column at
 * x=960: the edge begins at rgb(171,136,71) and falls away inward. The warm band
 * is deliberately NARROW — it starts at 96% of the 1306px radius, which is 52px
 * in. Earlier passes started it at 85% and 94%, and both washed amber a long way
 * down the sphere's face; the render keeps its light on the rim.
 */
const sphereStyle = {
  background: `radial-gradient(
    circle closest-side at 50% 50%,
    rgb(17, 16, 14) 0%,
    rgb(18, 16, 14) 88%,
    rgb(24, 21, 16) 93%,
    rgb(32, 25, 15) 96%,
    rgb(58, 45, 26) 97.8%,
    rgb(101, 81, 43) 98.8%,
    rgb(171, 136, 71) 100%
  )`,
  maskImage: `${LIMB_FADE}, ${EDGE_FADE}`,
  WebkitMaskImage: `${LIMB_FADE}, ${EDGE_FADE}`,
  maskComposite: "intersect",
  WebkitMaskComposite: "source-in",
}

const { data: stats } = await useAsyncData(
  "members-stats",
  () => getMembershipStats(),
  { default: () => [] },
)
</script>

<template>
  <!-- `isolate` so the glow can sit at `-z-10` without sliding behind the
       section's own background. -->
  <section
    class="relative isolate flex snap-screen min-h-[640px] flex-col items-center justify-center overflow-hidden bg-linear-to-b from-[#262626] to-[#0e0e0e] px-5 pt-36 pb-16 md:px-10 lg:px-20 lg:pt-[var(--nav-clearance)] lg:pb-[5.36vw]"
  >

    <!-- The globe — `401:19063`, built in CSS against `decor-hero-globe.png`,
         which is the designer's own 1920 x 741 render and stays in the repo as
         the thing this is matched to.

         **One positioned box, everything else a percentage of it.** The sphere,
         its halo and the map used to be three siblings positioned against the
         SECTION — which worked at 1920 x 1080 and nowhere else, because `top` is
         a share of the section's HEIGHT while `width` is a share of its WIDTH. On
         a 390 x 844 phone those two diverge hard: the map's box came out
         portrait, so the continents were squeezed into a tall narrow rectangle,
         and the arc drew a tight dome behind the title instead of a horizon. Now
         this box IS the sphere and the other two are sized off it, so the whole
         system scales as one thing and only this element knows about
         breakpoints.

         **The geometry is measured off the render.** Its arc rises ~420px above
         where it leaves the frame across a half-width of 960, and a circle
         through those points has radius (420^2 + 960^2) / (2 x 420) = 1307 — so
         the sphere is 2614 wide in a 1920 frame, which is 136%.

         The frame shows the middle ~74% of the sphere at every width, which is
         what keeps the arc the same SHAPE everywhere. What changes per breakpoint
         is how much sphere there is: a narrow screen needs a bigger circle to get
         a flat horizon out of it, and it wants that horizon lower down, under the
         copy rather than behind it.

         `--edge-r` rides along for the same reason — see `EDGE_FADE`. It is set
         here rather than in the style object because it has to change per
         breakpoint, and an inline style cannot hold a media query. -->
    <div
      aria-hidden
      class="pointer-events-none absolute top-[56%] left-1/2 -z-10 aspect-square w-[240%] max-w-none -translate-x-1/2 [--edge-r:24.5%] md:top-[46%] md:w-[172%] md:[--edge-r:34%] lg:top-[38%] lg:w-[136%] lg:[--edge-r:44%]"
    >
      <!-- The halo: the rim's light spilling outward into the dark.

           A SECOND circle sharing the sphere's centre. The sphere is clipped by
           `rounded-full`, so nothing painted on it can reach past its own edge —
           every glow tried on the sphere itself stopped dead at the horizon and
           the sky above went abruptly black.

           114.7% of the sphere, centred on it. That is the old 156/136 pair
           reduced to one ratio, which is the point of nesting: the two circles
           can no longer drift out of concentricity when a width changes.

           Its stops are measured — see `haloStyle`. It is a RING, not a disc:
           filled to the centre, the bright interior showed straight through
           wherever the sphere's own mask had faded, washing the lower half. -->
      <div
        class="absolute top-1/2 left-1/2 aspect-square w-[114.7%] max-w-none -translate-x-1/2 -translate-y-1/2 rounded-full"
        :style="haloStyle"
      />

      <!-- The sphere. Its fill is measured off the render — see `sphereStyle`.

           **There is no bright stroke, and that was the mistake.** Three passes
           put a near-white line on this edge. The render has nothing of the kind:
           its brightest pixel on the sphere is rgb(171,136,71), luminance 138,
           and the peak of the whole image — luminance 187 — sits OUTSIDE the
           sphere, in the halo. The rim is not drawn on the planet. It is the
           inside edge of its atmosphere.

           `closest-side` is load-bearing. A `radial-gradient(circle at 50% 50%)`
           defaults to `farthest-corner`, so on a square box 100% lands at root-2
           times the radius — every rim stop written at 97-99% is then drawn
           outside the circle and clipped away by `rounded-full`. That is why
           three rounds of making the rim brighter changed nothing: it was never
           on screen. -->
      <div class="absolute inset-0 rounded-full" :style="sphereStyle" />

      <!-- The continents, drifting across the sphere.

           **It drifts sideways, and the direction is not a preference.** Asked
           for upward, tried upward, and upward cannot loop: turning a globe
           vertically means tumbling it over its poles, and a world map will not
           do that. Longitude wraps — sail west far enough and you arrive back
           east — so a map scrolled sideways meets itself. Latitude does not. A
           map scrolled upward runs off its own top edge and the next copy starts
           at the Arctic, which is the cut that showed in the loop. No mask hides
           it for a whole lap; it crosses the frame once every time round.

           Sideways is also what a globe actually does. Two copies side by side,
           translated by exactly half the pair's width so copy two lands where
           copy one began — the join is Pacific meeting Pacific, which is where
           the map's own edges already agree.

           Sized off the SPHERE, not off the section: 42.7% of the circle wide and
           21.5% of it tall, which is the 1114 x 562 it measured at the design
           width. Two shares of the same square cannot come apart the way a share
           of the width and a share of the height did.

           `rotateX` lays the plane onto the sphere. `perspective` is in `vw` so
           the foreshortening scales with the globe instead of staying a fixed
           1100px, which on a phone tilted the map almost flat.

           The fade masks live on this OUTER element, not on the copies: they
           describe where the sphere is lit, which does not move. Only the map
           moves. -->
      <div class="absolute inset-0 [perspective:58vw] [perspective-origin:50%_0%]">
        <div
          class="absolute top-[0.84%] left-1/2 h-[21.5%] w-[42.7%] -translate-x-1/2 overflow-hidden [transform:rotateX(57deg)]"
          style="
            mask-image:
              radial-gradient(ellipse 66% 74% at 50% 26%, #000 18%, rgba(0, 0, 0, 0.55) 48%, transparent 78%),
              linear-gradient(180deg, transparent 0%, rgba(0, 0, 0, 0.5) 7%, #000 20%, #000 62%, transparent 92%),
              linear-gradient(96deg, rgba(0, 0, 0, 0.22) 0%, rgba(0, 0, 0, 0.75) 22%, #000 42%, #000 80%, rgba(0, 0, 0, 0.45) 100%);
            -webkit-mask-image:
              radial-gradient(ellipse 66% 74% at 50% 26%, #000 18%, rgba(0, 0, 0, 0.55) 48%, transparent 78%),
              linear-gradient(180deg, transparent 0%, rgba(0, 0, 0, 0.5) 7%, #000 20%, #000 62%, transparent 92%),
              linear-gradient(96deg, rgba(0, 0, 0, 0.22) 0%, rgba(0, 0, 0, 0.75) 22%, #000 42%, #000 80%, rgba(0, 0, 0, 0.45) 100%);
            mask-composite: intersect;
            -webkit-mask-composite: source-in;
          "
        >
          <div class="globe-drift absolute inset-y-0 left-0 w-[200%]">
            <div
              class="globe-dots absolute inset-y-0 left-0 w-1/2"
              style="
                mask-image: url('/assets/members/decor-map-frame.svg');
                -webkit-mask-image: url('/assets/members/decor-map-frame.svg');
              "
            />
            <div
              class="globe-dots absolute inset-y-0 left-1/2 w-1/2"
              style="
                mask-image: url('/assets/members/decor-map-frame.svg');
                -webkit-mask-image: url('/assets/members/decor-map-frame.svg');
              "
            />
          </div>
        </div>
      </div>
    </div>

    <div class="flex w-full max-w-[1200px] flex-col items-center gap-8 lg:gap-16">
      <!-- Inter Medium 84, centred. -->
      <h1
        class="font-sans text-center text-[length:var(--text-page-title)] leading-[1.1] font-medium text-white"
      >
        {{ MEMBERS_COPY.heroTitle }}
      </h1>

      <!-- 728 of the design's 1920, centred under the title. -->
      <p
        class="font-sans max-w-[728px] text-center text-[length:var(--text-eyebrow)] leading-8 text-white/60"
      >
        {{ MEMBERS_COPY.heroIntro }}
      </p>
    </div>

    <!-- 604 − 443 = 161px below the copy at the design width. `401:19075` is the
         landing page's gold pill exactly — the same radial fill, the same 3px
         conic stroke, the same glow, the same 48px radius and Bebas 36 label
         through the ink gradient. So it is `GoldCta`, not a second button that
         happens to look like it. -->
    <UiGoldCta
      :href="MEMBERS_COPY.heroCtaHref"
      class="mt-10 lg:mt-[8.39vw] lg:w-[340px]"
    >
      {{ MEMBERS_COPY.heroCta }}
    </UiGoldCta>

    <!-- `404:19188` — four figures across the foot, 129px below the pill. A
         `<dl>` because each is a label and a value; the design puts the value
         above the label, which `flex-col-reverse` gives without reversing the
         markup.

         A QUARTER of the row each from `lg`, not Figma's 400px. Four fixed 400s
         need 1600 and a 1280 laptop leaves 1120, so they wrapped to two rows —
         which pushed the section to 910px inside an 800px window and spilled the
         last two figures below the fold of their own snap stop. A share of the
         row is 400 at the design width and still one row at 1280. -->
    <dl
      class="mt-12 flex w-full flex-wrap items-start justify-center gap-x-3 gap-y-10 lg:mt-[6.72vw]"
    >
      <div
        v-for="stat in stats"
        :key="stat.id"
        class="flex w-[calc(50%-0.75rem)] flex-col-reverse items-center gap-6 lg:w-[calc(25%-0.75rem)]"
      >
        <dt
          class="font-sans text-center text-[length:var(--text-body-md)] leading-[1.25] font-medium text-white/80"
        >
          {{ stat.label }}
        </dt>
        <!-- Bebas 100 through the page's gold gradient. The gradient is painted
             through the glyphs, so it has to stay on the element the text is in
             — `CountUp` renders spans inside this one and none of them
             re-declare a fill. -->
        <dd
          class="font-display text-gold-gradient text-center text-[length:var(--text-display-statement)] leading-none"
        >
          <MotionCountUp :value="stat.value" />
        </dd>
      </div>
    </dl>
  </section>
</template>
