// app/components/tournaments/Hero.vue
<script setup lang="ts">
import type { ShowcaseEvent } from "~/lib/api/types"
import { TOURNAMENTS_COPY } from "~/content/tournaments"

/**
 * The page's opening block — Figma node `370:17243`.
 *
 * A gold radial ground with the federation emblem sunk into it, a light sweep
 * across the top, the trophy standing in the middle, "DWF2026" laid across it at
 * 400px, and a blurred bar along the foot carrying the event and the stream
 * button.
 *
 * **The event is the same record the band below prints.** The design names it
 * "Caribbean Domino Open 2026" here and "CARIBBEAN DOMINO OPEN 2024" there, with
 * the same dates under both — two spellings of one tournament, which on a live
 * page would be a defect rather than a variation. Both blocks read
 * `getHighlightedTournament()`, so they cannot disagree.
 *
 * The layers are stacked, not parallaxed: this is a page header rather than the
 * landing hero, and nothing in the design suggests depth here (RULES §12 keeps
 * parallax to where it was drawn).
 */
defineProps<{ event: ShowcaseEvent }>()
</script>

<template>
  <!-- The radial is Figma's own (`370:17244`): a circle struck at the top
       centre, gold falling to bronze. `min-h` rather than the design's 1083 so a
       long event name grows the block instead of overflowing it. -->
  <!-- One screen: `581:14547` is 1920 × 1080, like the "All tournaments" band
       under it. `snap-screen` rather than the design's ratio — the two agree only
       at 16:9, and a 1512 × 900 laptop is left short by the ratio alone. -->
  <section
    aria-labelledby="tournament-hero-heading"
    class="relative isolate flex snap-screen flex-col justify-end overflow-hidden bg-[radial-gradient(circle_at_50%_0%,#c3ae86_0%,#4f4332_100%)]"
  >
    <!-- Three layers, three speeds, and the order is the point: depth is read
         from RATE, so the emblem sunk into the ground trails, the light wash
         above it moves a little more, and the trophy — the subject — leads
         (RULES §12). All three on `transform` only, and well under the 3–4
         moving layers a viewport is allowed.

         `anchor="top"` on every one of them, which is mandatory for a hero: the
         default `cross` range opens when the section's head meets the viewport's
         FOOT, so a page that has not been scrolled yet already sits partway
         along it and every layer renders pre-shifted — visibly detached from the
         edge it is supposed to start at (D16). -->

    <!-- The emblem, 8% black and sunk into the ground rather than lit on top of
         it (`371:17302`). Decorative, and the slowest thing here. -->
    <MotionParallaxLayer
      :speed="4"
      anchor="top"
      decorative
      class="pointer-events-none absolute top-[10%] left-1/2 -z-10 w-[28.5vw] max-w-[547px] -translate-x-1/2"
    >
      <img
        src="/assets/tournaments/decor-hero-emblem.svg"
        alt=""
        aria-hidden
        class="w-full opacity-[0.08]"
      >
    </MotionParallaxLayer>

    <!-- The light sweep across the top (`371:17308`), wider than the frame in
         the design and left that way — it is a wash, and cropping it at the
         edges is what makes it read as light rather than as a shape. -->
    <MotionParallaxLayer
      :speed="7"
      anchor="top"
      decorative
      class="pointer-events-none absolute -top-[19%] left-1/2 -z-10 w-[121vw] max-w-none -translate-x-1/2"
    >
      <img
        src="/assets/tournaments/decor-hero-shade.svg"
        alt=""
        aria-hidden
        class="w-full"
      >
    </MotionParallaxLayer>

    <!-- The trophy. `priority` because it is this page's LCP, the same call
         `/domino` and `/development` make for their opening images.

         NOT `decorative`: it carries a real `alt`, so the layer must not be
         hidden from assistive tech the way the two washes above it are. -->
    <MotionParallaxLayer
      :speed="14"
      anchor="top"
      class="pointer-events-none absolute inset-x-0 top-[2.6%] -z-10 flex justify-center"
    >
      <div class="flex w-full justify-center">
        <NuxtImg
          src="/assets/tournaments/hero-trophy-hand.png"
          :alt="TOURNAMENTS_COPY.hero.portraitAlt"
          :width="728"
          :height="1304"
          preload
          loading="eager"
          fetchpriority="high"
          :sizes="imageSizes({ xs: '60vw', lg: '38vw' })"
          class="h-auto w-[60vw] max-w-[728px] lg:w-[38vw]"
        />
      </div>
    </MotionParallaxLayer>

    <!-- Bebas 400 with a white-to-transparent fall (`372:17399`). Decorative: it
         is the tournament's own branding, and the heading below names the event
         for anyone who cannot see it. Sized as a fraction of the window so it
         keeps its place across the trophy at every width.

         **`leading-[0.9]`, and the tops of the letters are why.** This is a
         gradient behind `bg-clip-text`, and a background is only painted inside
         the element's box — so a line box shorter than the glyphs does not
         overflow them, it ERASES the part that sticks out. Bebas caps run about
         0.73em and the leading was 0.7, which shaved the head off every letter
         in the wordmark. The same trap is recorded on the countdown's digits,
         where tightening the leading IS safe because those are a flat colour.

         `-mt-[0.1em]` puts it back where it was: the box grew by 0.2em and the
         ink centres in it, so the text had dropped by half of that. `em` here
         resolves against this element's own font size, which is a fraction of
         the window — so the correction tracks the type at every width instead of
         being a pixel guess against the section's height. -->
    <p
      aria-hidden
      class="font-display pointer-events-none absolute inset-x-0 top-[58%] -z-10 -mt-[0.1em] bg-linear-to-b from-white to-transparent bg-clip-text text-center text-[20.83vw] leading-[0.9] tracking-[-0.0492em] text-transparent"
    >
      {{ TOURNAMENTS_COPY.hero.watermark }}
    </p>

    <!-- The foot bar (`370:17245`): a fall to the page's own black.

         Figma also puts a 15px backdrop blur on this frame, and it is not
         reproduced. A backdrop filter applies at full strength across the whole
         box while the gradient over it starts at transparent, so the blur's top
         edge lands as a straight line ruled across the artwork — here it cut the
         DWF2026 wordmark in half. The gradient alone is what the effect is for:
         the trophy softens into the block below without a seam. Reported from a
         screenshot, and the same fix applies to the news page's featured
         shelf. -->
    <div
      class="relative flex flex-col gap-8 bg-linear-to-b from-transparent via-[#0e0e0e]/75 to-[#0e0e0e] px-5 pt-24 pb-10 md:px-10 lg:flex-row lg:items-end lg:justify-between lg:gap-16 lg:px-20 lg:pt-[6vw] lg:pb-[4.17vw]"
    >
      <div class="flex flex-col gap-2.5">
        <!-- Bebas 32/40 at half opacity (`370:17247`). The bullet is
             `aria-hidden`: it separates two fields for the eye, and read aloud
             it is noise between a place and a date. -->
        <p
          class="font-display flex flex-wrap items-center gap-2.5 text-[length:var(--text-display-caption)] leading-[1.25] text-white/50 uppercase"
        >
          <span>{{ event.location }}</span>
          <span aria-hidden>{{ TOURNAMENTS_COPY.hero.separator }}</span>
          <span>{{ event.dateLabel }}</span>
        </p>

        <!-- Inter SemiBold 64/72 (`370:17251`), capped at the design's 1080 so a
             long name breaks where the design breaks it. -->
        <h1
          id="tournament-hero-heading"
          class="font-sans max-w-[1080px] text-[length:var(--text-heading-hero)] leading-[1.125] font-semibold text-white"
        >
          {{ event.name }}
        </h1>
      </div>

      <!-- 320 × 72 flat gold at 8px radius (`372:17392`) — not `GoldCta`, which
           is the landing page's 48px pill with a glow and a travelling sheen.
           Same brand colour, different control. -->
      <TournamentsUnavailableButton
        :notice="TOURNAMENTS_COPY.hero.watchLiveUnavailable"
        class="rounded-btn font-display focus-visible:ring-gold bg-gold flex h-18 w-full items-center justify-center gap-4 px-5 text-[length:var(--text-display-cta)] leading-11 text-black uppercase transition-colors hover:bg-[var(--color-gold-btn-light)] focus-visible:ring-2 focus-visible:outline-none lg:w-80"
      >
        {{ TOURNAMENTS_COPY.hero.watchLive }}
        <img
          src="/assets/tournaments/icon-live-stream.svg"
          alt=""
          width="32"
          height="32"
          class="size-8"
        >
      </TournamentsUnavailableButton>
    </div>
  </section>
</template>

// src/components/sections/Hero.tsx
import { HERO_ALT, HERO_COPY } from "@/content/hero"
import { SofteningImage } from "@/components/ui/SofteningImage"
import { GoldCta } from "@/components/ui/GoldCta"
import { ParallaxLayer } from "@/components/ui/ParallaxLayer"
import { DURATION } from "@/lib/utils/motion"

/**
 * Seconds. How long the rocks take to retreat, and how long their softening
 * takes — the two are one move and must be given the same number or the blur
 * lands before the scale does.
 *
 * Longer than a standard entrance (`DURATION`) because the rocks are the
 * largest things on the page and travel the furthest: the same duration that
 * suits a line of copy reads as a lurch across a shelf of rock.
 */
const HERO_RETREAT = DURATION * 1.5

/**
 * Seconds. The tile arrives on top of the rocks' retreat rather than after it —
 * roughly a third of the way in, so the two overlap instead of queueing.
 */
const TILE_DELAY = HERO_RETREAT / 3

/**
 * S2 — Figma node `22:789`. The main parallax section.
 *
 * The design only exists at 1920 × 1040, and every layer in it is placed as a
 * percentage of that frame. Those percentages are only meaningful on a box with
 * roughly that ratio, so the artwork lives in its own "stage" element that
 * keeps a wide ratio at every width. Below `lg` the stage is a normal block and
 * the copy flows underneath it; from `lg` up the stage fills the section and the
 * copy is placed over it exactly as in Figma.
 *
 * Stacking follows the child order in Figma, which is deliberate: the headline
 * sits at the very bottom so the domino tile crosses in front of the word
 * "WITHOUT". Because every layer carries an explicit z-index, DOM order is free
 * to differ — it is chosen for the mobile flow instead.
 *
 * Depth comes from the blur baked into the design (DESIGN-TOKENS §5): the more
 * blurred a layer, the further away it reads, and the slower it travels.
 *
 * On load the composition assembles itself. Both rocks start at full size and
 * sharp, then shrink towards the corner they are anchored to — top-right for
 * the upper one, bottom-left for the lower — so their outer edge stays pinned
 * and they retreat inwards rather than drifting away from the frame, going
 * soft as they go. The tile arrives while that retreat is still under way, out
 * of focus at first and then settling into the design's own slight blur.
 *
 * `SofteningImage` does the focus changes without animating `filter`. The
 * entrance is a one-off; scroll parallax takes over afterwards.
 *
 * Three moving layers, which is the per-viewport ceiling (RULES §12).
 */
export function Hero() {
  return (
    // `54.17vw` IS the design's ratio — 1040/1920 — so at 1920 the section is
    // 1040px tall and every percentage inside it is Figma's own. The `max()`
    // puts a floor under it, because the ratio alone makes a narrower window
    // give a shorter hero (780px at 1440, 693px at 1280) while the things
    // stacked inside it do not shrink at all: the CTA is 72px and the two copy
    // rows ~132px whatever the width. The content stops fitting below ~1480px,
    // which is exactly where the button began overlapping "WITHOUT" — measured
    // at 7px of bite at 1440 and 26px at 1280. Each extra pixel of height buys
    // 0.56 of gap (the headline sits at 0.44H while the block hangs off the
    // bottom), so clearing it with a readable margin takes 840.
    //
    // Written as a height and NOT as `aspect-[1920/1040] min-h-[840px]`, which
    // was the first attempt and is a trap: `aspect-ratio` resolves in both
    // directions, so the floor fed back through the ratio and forced the
    // section 1551px WIDE — the entire page scrolled sideways at every width
    // below that (measured `scrollWidth` 1551 against a 1280 viewport). A
    // height cannot push the width around.
    <section className="from-hero-top to-hero-bottom relative isolate flex min-h-dvh flex-col overflow-hidden bg-linear-to-b lg:h-[max(840px,54.17vw)] lg:min-h-0">
      {/* The stage IS the coordinate space, at every width: `inset-0` means a
          layer's percentages are percentages of the section.

          From `lg` the section carries the design's own 1920 × 1040 ratio, so
          those percentages are Figma's, unaltered. Below `lg` the same box is
          portrait, and each layer carries a second set of numbers.

          A single scaled frame was tried first and is what produced the mess
          the phone showed: a 1920 × 1040 box is only ~210px tall on a 390px
          screen, so the whole composition compressed into a band under the
          navbar and left a dead grey void between the headline and the CTA —
          a quarter of the screen with nothing in it. Widening the frame to
          fill that height is not available either, because every layer is
          sized as a fraction of the frame: the tile grows at the same rate and
          swallows the headline it is meant to pass behind.

          So the phone gets its own arrangement of the same three layers, keeping
          the design's diagonal — rock upper-right, tile through the middle,
          rock lower-left — spread over the full height instead of stacked in
          one band. `overflow-hidden` on the section clips the rocks' overhang,
          so nothing widens the page. */}
      {/* `z-10` is what puts the artwork in front of the headline. Without it
          the stage is `z-auto`, which is NOT a stacking context — so its
          children do not compete with the headline as a group. Each layer's
          own z-index is then resolved against the section directly, and the
          headline, painted later in DOM order at the same effective level,
          wins on tie-break and covers the tile. Giving the stage a real
          z-index makes the whole group outrank `z-0`, and the tile crosses in
          front of "WITHOUT" as the Figma child order intends.

          It pairs with `isolate` on the section: that keeps these indices —
          and the CTA block's `z-60` — a private scale, so nothing here can
          outrank the navbar's `z-50` in the page's root context. */}
      <div className="absolute inset-0 z-10">
        {/* Rocks are the heaviest layers, and were once dropped below md to
            spare low-end phones the compositing. They are kept now because
            without them the phone layout is not the same design — three
            moving layers either way, which is the per-viewport ceiling
            (RULES §12).

            Upper-right on both, but far wider on a phone: a rock at Figma's
            45% of a portrait box is a small chip floating in grey, where at
            1920 the same fraction is a broad shelf. Sized to the viewport
            instead, it keeps the design's weight and its outer edge runs off
            the screen exactly as the design's runs off the frame. */}
        <ParallaxLayer
          speed={12}
          enter={{ scale: [1, 0.82], duration: HERO_RETREAT }}
          origin="topRight"
          anchor="top"
          decorative
          className="absolute top-[7%] left-[42%] z-10 w-[70%] lg:top-0 lg:left-[47.6%] lg:w-[45.4%]"
        >
          {/* `priority` even though the rock is decorative: it is the biggest
              thing painted above the fold, so Next measures it as the LCP
              element and warns that it loads lazily. Being decorative makes it
              MORE important to preload, not less — the entrance animation
              starts on mount whether or not the bitmap has arrived, so a lazy
              rock plays its 1.6s retreat as an empty box and pops in late. */}
          <SofteningImage
            src="/assets/global/decor-rock-top.png"
            alt=""
            width={888}
            height={361}
            priority
            from="0px"
            to="4px"
            duration={HERO_RETREAT}
          />
        </ParallaxLayer>

        {/* This one carries the phone layout. The gap between the headline and
            the CTA was the dead quarter of the screen; the lower rock is
            placed to run through it, so the eye travels headline → rock → CTA
            down the same left-leaning diagonal the design uses. `-left-[10%]`
            lets it bleed off the left edge rather than sit inside a margin. */}
        <ParallaxLayer
          speed={6}
          enter={{ scale: [1, 0.82], duration: HERO_RETREAT }}
          origin="bottomLeft"
          anchor="top"
          decorative
          className="absolute top-[43%] -left-[16%] z-20 w-[78%] lg:top-[62.5%] lg:left-[8.4%] lg:w-[49.2%]"
        >
          {/* Same reasoning as the upper rock — Next flagged this one as LCP
              too, since which of the two wins depends on the viewport. */}
          <SofteningImage
            src="/assets/global/decor-rock-bottom.png"
            alt=""
            width={970}
            height={403}
            priority
            from="0px"
            to="6.5px"
            duration={HERO_RETREAT}
          />
        </ParallaxLayer>

        {/* Height is pinned as well as width: Figma crops this one to a
            585 × 636 box (`objectFit: cover`). Letting the native 1882 × 2267
            ratio decide would make the tile a tenth taller than the design.

            The phone numbers are chosen against the headline, which wraps to
            two lines there where the design has one: the tile is held to 30%
            of the viewport — the share it takes at 1920 — and its bottom edge
            stops inside the first line, so it crosses "WITHOUT" and leaves the
            second line completely clear. Measured per line with
            `Range.getClientRects()`: 46–50% of line one, 0% of line two.

            Comes in while the rocks are still retreating — it starts around
            a third of the way into their 1.6s and lands before they settle,
            so the two overlap instead of queueing.

            It straightens as it arrives. The asset is drawn 26.3° off
            vertical already and Figma adds no rotation of its own, so `0` is
            the raw lean — it starts there and pulls back to the resting
            angle, which reads as the tile righting itself rather than
            switching on. It stops well short of upright; the slant is the
            design. */}
        <ParallaxLayer
          speed={24}
          enter={{
            opacity: [0, 1],
            scale: [0.8, 0.8],
            rotate: [-16, -6],
            duration: DURATION,
            delay: TILE_DELAY,
          }}
          anchor="top"
          className="absolute top-[16%] left-[43%] z-30 h-[15%] w-[30%] lg:top-[16.9%] lg:left-[35.3%] lg:h-[61.2%] lg:w-[30.5%]"
        >
          {/* The PNG, not the SVG next to it: that SVG is the very same
              1882 × 2267 raster wrapped in base64, so it buys no sharpness —
              it only costs 1.4 MB and, being an SVG, skips the optimiser
              entirely. `quality` is raised because the tile is the one image
              the eye actually lands on, and the default flattens its gold. */}
          <SofteningImage
            src="/assets/home/hero-domino-tile.png"
            alt={HERO_ALT.dominoTile}
            fill
            sizes="(max-width: 1024px) 30vw, 31vw"
            priority
            quality={90}
            from="10px"
            to="2px"
            duration={DURATION}
            delay={TILE_DELAY}
            imageClassName="object-contain"
          />
        </ParallaxLayer>

        {/* Grounds the composition into the page background. Figma specifies
            a circle, but at this box ratio its top corners are already opaque
            and leave a hard horizontal seam — a wide ellipse keeps the whole
            top edge transparent while the falloff still matches.

            `lg` only, and deliberately: it fades to `--color-bg`, which is the
            right colour where the design's own vignette sits. On a phone the
            section is still mid-gradient at its foot, so the same fade reads
            as a dark band — and nothing there needs grounding, because the
            rocks stop well short of the bottom edge. */}
        <div
          aria-hidden="true"
          className="absolute inset-x-0 bottom-0 z-40 hidden h-[36%] bg-[radial-gradient(ellipse_130%_100%_at_51%_0%,transparent_47%,var(--color-bg)_100%)] lg:block"
        />
      </div>

      {/* `mt-auto` here and on the CTA block below splits the leftover height
          between them, which lands the tagline/headline pair near the middle
          of the section — where `lg` puts it explicitly at 36%/44%. Pinning it
          under the navbar instead left the words at the top and the artwork
          orphaned below them.

          `pt-28` reserves the navbar's band. The navbar overlays the hero
          rather than occupying its own row, so without it `mt-auto` is free to
          centre the tagline right under the logo — the two then print on top
          of each other. The padding is part of the flex item, so it is counted
          before the leftover space is split. */}
      {/* The copy is deliberately still. The hero's entrance is the artwork
          assembling itself on load, and that is the whole of it — the words are
          what the moving pieces resolve into, so they are already in place when
          the rocks start to retreat.

          A scroll-triggered `Reveal` was tried here and taken back out: this
          section is on screen at load, so a scroll entrance either fires
          immediately (adding a second, competing entrance to the one the layers
          already play) or waits for a scroll that has nothing left to reveal. */}
      <p className="font-sans relative z-50 mt-auto pt-28 bg-linear-to-r from-white via-[var(--color-silver-mid)] to-white bg-clip-text px-5 text-center text-base font-semibold tracking-[0.24em] text-transparent uppercase lg:absolute lg:inset-x-0 lg:top-[36%] lg:mt-0 lg:pt-0 lg:text-2xl">
        {HERO_COPY.tagline}
      </p>

      {/* z-0 — behind every image, per the Figma child order. */}
      <h1 className="font-display relative z-0 mt-3 bg-linear-to-r from-white via-[var(--color-silver-mid)] to-white bg-clip-text px-5 text-center text-[length:var(--text-display-lg)] leading-none text-transparent uppercase lg:absolute lg:inset-x-0 lg:top-[44%] lg:mt-0">
        {HERO_COPY.headline}
      </h1>

      {/* Anchored to the bottom (`mt-auto`), so both the gap and the bottom
          padding push the CTA upwards. Figma leaves 63px between the button
          and the mission copy, and 107px below the last element.

          At `lg` those two are written as `vw`, not as the raw px. The section's
          height is pinned to its width by `aspect-[1920/1040]`, so it shrinks as
          the window narrows — but fixed padding does not, and the block ends up
          claiming a larger and larger share of a smaller and smaller hero.
          Measured: 373px tall at every width, which is 36% of the hero at 1920
          but 48% at 1440, where it had climbed 51px into the headline.

          3.33vw and 5.6vw are Figma's own 64 and 108 divided by 1920, so the
          design width still renders the design's numbers exactly, and every
          narrower one keeps the same proportion instead of the same pixels. */}
      <div className="relative z-60 mt-auto flex flex-col gap-10 px-5 pt-12 pb-10 md:px-10 lg:gap-[3.33vw] lg:px-20 lg:pt-0 lg:pb-[5.6vw]">
        {/* 340 × 72 in Figma (`31:1117`); the height is set by the component.
            `max-w-70` on a phone, not the full 340: at 390px wide the design's
            width fills 87% of the screen, where at 1920 the same button takes
            18% — so carrying the raw number across turns a compact capsule
            into a bar spanning the viewport. The pill radius is a fixed 48px,
            which caps how wide it can go before the capsule reads as a rounded
            rectangle. From `sm` the screen is wide enough for Figma's own
            340. */}
        <GoldCta href="#" className="mx-auto w-full max-w-70 sm:max-w-85">
          {HERO_COPY.primaryCta}
        </GoldCta>

        {/* Figma sets the two copy blocks against opposite edges. That reads as
            a pair only while they sit side by side; stacked on a phone, one
            ragged-left and one ragged-right block just looks misaligned — so
            below `lg` both centre, and the CTA stretches to the column. */}
        <div className="flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between">
          {/* Figma's own 432px block, narrowed between `menu` and `menu-lg`.
              That is exactly the band where the countdown card has been pulled
              up into this row: the card is a fixed 498px and centred, so the
              space on each side is `(vw − 498) / 2 − 80` of gutter, which at
              1400 is 371px against a 432px block. 288px clears it; from
              `menu-lg` the row is wide enough for the design's own width. */}
          <p className="font-sans max-w-108 text-center text-base leading-[26px] text-white lg:text-left lg:text-lg menu:max-w-72 menu-lg:max-w-108">
            {HERO_COPY.mission}
          </p>

          <div className="flex flex-col gap-4 lg:items-end">
            <p className="font-sans max-w-79 text-center text-base leading-[26px] text-white lg:text-right lg:text-lg">
              {HERO_COPY.accountability}
            </p>
            <a
              href="#"
              className="rounded-btn font-display focus-visible:ring-gold flex items-center justify-center bg-white/20 px-5 py-4 text-[length:var(--text-display-btn)] leading-none text-white uppercase focus-visible:ring-2 focus-visible:outline-none lg:w-73"
            >
              {HERO_COPY.secondaryCta}
            </a>
          </div>
        </div>
      </div>
    </section>
  )
}
