// src/app/faq/page.tsx
import type { Metadata } from "next"

import { FaqBoard } from "@/components/faq/FaqBoard"
import { FaqCategoryTabs } from "@/components/faq/FaqCategoryTabs"
import { FaqSearch } from "@/components/faq/FaqSearch"
import { Footer } from "@/components/layout/Footer"
import { Navbar } from "@/components/layout/Navbar"
import { PageHeader } from "@/components/ui/PageHeader"
import { SideTabLayout } from "@/components/ui/SideTabLayout"
import { SupportCard } from "@/components/ui/SupportCard"
import { FAQ_PAGE_COPY } from "@/content/faq"
import { FAQ_PAGE_ITEMS, type FaqPageItem } from "@/content/faq/items"

export const metadata: Metadata = {
  title: "FAQ | Domino World Federation",
  description:
    "Answers to common questions about sanctioned dominoes — how tournaments are entered, what the standard set holds, and how a hand is played and scored.",
}

/**
 * `/faq` — Figma screen `173:9459`.
 *
 * The eleventh page, and the fourth on the side-tab shell: the band from
 * `ui/PageHeader`, the two columns from `ui/SideTabLayout`, the card from
 * `ui/SupportCard` (D57). What it does not share is the body — a filtered
 * accordion is not a numbered document, so it is not built on `LegalDocument`
 * even though that component's note offered to take this screen.
 *
 * **Until now the footer's "FAQ" link went to `/#faq`**, the landing page's S11
 * — three questions in a section, standing in for a page that had been drawn
 * but not built. It points here now, and S11 keeps its anchor.
 *
 * **The questions are copy, not data.** They live in `content/faq/`, like the
 * legal clauses and unlike the news feed: an FAQ is a document the federation
 * writes, not a feed it files, so routing it through a mock endpoint would
 * promise a `/faq` response nobody is going to build (the call `/terms` made).
 * That leaves both filters in the same place — the URL, read on the server —
 * so `?category=` and `?q=` behave like `/gallery`'s `?event=` and the news
 * archive's `?category=` (D50): shareable, no client island, no second copy of
 * the state.
 *
 * **The pager is not built.** The design draws one under the card
 * (`174:10695`): three numbered pages, of which it fills the first with ten
 * questions. There are ten questions in the whole file, so pages two and three
 * would be empty — and a control that leads somewhere empty is the silent
 * no-op D28 ruled out, the same reason the Domino rulebook tabs were left alone
 * (D42). Recorded as R15; it becomes a five-minute component the moment the
 * copy for pages two and three exists.
 *
 * Renders dynamically (`ƒ`) because it reads `searchParams`, as `/gallery` and
 * `/news` do.
 */
export default async function FaqPage({
  searchParams,
}: {
  searchParams: Promise<{ category?: string; q?: string }>
}) {
  const { category, q } = await searchParams

  const term = q?.trim().toLowerCase() ?? ""

  // Filtered in two passes so the two controls compose: narrowing to a topic
  // and then searching inside it is the combination the hidden field in
  // `FaqSearch` and the forwarded `q` in `FaqCategoryTabs` both assume.
  const inCategory = category
    ? FAQ_PAGE_ITEMS.filter((item) => item.category === category)
    : FAQ_PAGE_ITEMS

  const shown = term
    ? inCategory.filter((item) => matches(item, term))
    : inCategory

  return (
    // `relative` anchors the navbar, which is `fixed` and overlays the page.
    <div className="relative">
      <Navbar />

      <main>
        <PageHeader
          title={FAQ_PAGE_COPY.title}
          back={{ label: FAQ_PAGE_COPY.back, href: FAQ_PAGE_COPY.backHref }}
          aside={<FaqSearch query={q} category={category} />}
        />

        <SideTabLayout
          sidebar={
            <>
              {/* The whole list, not the filtered one: a filter that hides the
                  way back to the other topics is a dead end. */}
              <FaqCategoryTabs
                items={FAQ_PAGE_ITEMS}
                active={category}
                query={q}
              />
              <SupportCard />
            </>
          }
        >
          <FaqBoard
            // Remounts the accordion when the filter changes. Which item is
            // open is client state that outlives a server navigation, and it
            // is keyed by an id that the new list may not contain — without
            // this, filtering can land the reader on a card with every answer
            // shut.
            key={`${category ?? "all"}:${term}`}
            items={shown}
            empty={
              term ? (
                <>
                  {FAQ_PAGE_COPY.emptySearch.replace("%s", q ?? "")}{" "}
                  <a
                    href={category ? `/faq?category=${category}` : "/faq"}
                    className="focus-visible:ring-gold text-black underline decoration-from-font underline-offset-4 transition-colors hover:text-black/70 focus-visible:ring-2 focus-visible:outline-none"
                  >
                    {FAQ_PAGE_COPY.searchClear}
                  </a>
                </>
              ) : (
                FAQ_PAGE_COPY.empty
              )
            }
          />
        </SideTabLayout>
      </main>

      <Footer />
    </div>
  )
}

/**
 * Whether a question is a hit.
 *
 * Both the question and its answer are searched: a reader looking for
 * "boneyard" should find the question that explains it and the two that mention
 * it in passing. The answer's segments are joined because the bold runs are
 * typographic, not semantic — a phrase must not become unfindable for having
 * been emphasised mid-sentence.
 */
function matches(item: FaqPageItem, term: string) {
  const haystack = [
    item.question,
    ...item.answer.map((segment) => segment.text),
  ]
    .join(" ")
    .toLowerCase()

  return haystack.includes(term)
}

// app/pages/page/faq.vue
<script setup lang="ts">
import { FAQ_PAGE_COPY } from "~/content/faq"
import { FAQ_PAGE_ITEMS, type FaqPageItem } from "~/content/faq/items"

/**
 * `/page/faq` — Figma screen `613:23161`.
 *
 * **A sibling of `[key].vue`, not an entry in it.** The three side-tab documents
 * share a URL shape because the repo owner asked for one, and Nuxt resolves a
 * static segment ahead of a dynamic one, so this file takes `/page/faq` and the
 * parameter route is left with the documents it actually knows how to render. A
 * branch inside `[key].vue` would have been one route doing two unrelated jobs:
 * the legal pages are a numbered document with a table of contents, and this is
 * a filtered accordion with a search field and two URL-driven filters. They meet
 * at the shell, which is where D57 already drew the line.
 *
 * The fourth page on the side-tab shell: the band from
 * `ui/PageHeader`, the two columns from `ui/SideTabLayout`, the card from
 * `ui/SupportCard` (D57). What it does not share is the body — a filtered
 * accordion is not a numbered document, so it is not built on `LegalDocument`
 * even though that component's note offered to take this screen.
 *
 * **The redraw took the white card away.** `173:9459` put the questions in the
 * legal panel — black type on white, on a dark page; `613:23161` drops it and
 * lets the items stand on the screen's own ground as filled boxes. `FaqBoard`
 * carries the change and its note has the reasoning; the only thing it reaches
 * out here is the "clear search" link, which was black for the card it no longer
 * sits on.
 *
 * **The questions are copy, not data.** They live in `content/faq/`, like the
 * legal clauses and unlike the news feed: an FAQ is a document the federation
 * writes, not a feed it files, so routing it through a mock endpoint would
 * promise a `/faq` response nobody is going to build (the call `/terms` made).
 * That leaves both filters in the same place — the URL, read during SSR — so
 * `?category=` and `?q=` behave like `/gallery`'s `?event=` and the news
 * archive's `?category=` (D50): shareable, no client island, no second copy of
 * the state.
 *
 * **The pager is not built.** The design draws one under the card (`174:10695`):
 * three numbered pages, of which it fills the first with ten questions. There
 * are ten questions in the whole file, so pages two and three would be empty —
 * and a control that leads somewhere empty is the silent no-op D28 ruled out,
 * the same reason the Domino rulebook tabs were left alone (D42). Recorded as
 * R15; it becomes a five-minute component the moment the copy for pages two and
 * three exists.
 */
useSeoMeta({
  title: "FAQ | Domino World Federation",
  description:
    "Answers to common questions about sanctioned dominoes — how tournaments are entered, what the standard set holds, and how a hand is played and scored.",
})

const route = useRoute()

const category = computed(() =>
  typeof route.query.category === "string" ? route.query.category : undefined,
)
const q = computed(() =>
  typeof route.query.q === "string" ? route.query.q : undefined,
)

const term = computed(() => q.value?.trim().toLowerCase() ?? "")

/**
 * Whether a question is a hit.
 *
 * Both the question and its answer are searched: a reader looking for "boneyard"
 * should find the question that explains it and the two that mention it in
 * passing. The answer's segments are joined because the bold runs are
 * typographic, not semantic — a phrase must not become unfindable for having
 * been emphasised mid-sentence.
 */
function matches(item: FaqPageItem, needle: string) {
  return [item.question, ...item.answer.map((segment) => segment.text)]
    .join(" ")
    .toLowerCase()
    .includes(needle)
}

// Filtered in two passes so the two controls compose: narrowing to a topic and
// then searching inside it is the combination the hidden field in `FaqSearch`
// and the forwarded `q` in `FaqCategoryTabs` both assume.
const shown = computed(() => {
  const inCategory = category.value
    ? FAQ_PAGE_ITEMS.filter((item) => item.category === category.value)
    : FAQ_PAGE_ITEMS

  return term.value
    ? inCategory.filter((item) => matches(item, term.value))
    : inCategory
})

// Remounts the accordion when the filter changes. Which item is open is local
// state that would otherwise outlive the navigation, keyed by an id the new list
// may not contain — without this, filtering can land the reader on a card with
// every answer shut.
const boardKey = computed(() => `${category.value ?? "all"}:${term.value}`)

const clearHref = computed(() =>
  category.value ? `/page/faq?category=${category.value}` : "/page/faq",
)
</script>

<template>
  <main>
    <UiPageHeader
      :title="FAQ_PAGE_COPY.title"
      :back="{ label: FAQ_PAGE_COPY.back, href: FAQ_PAGE_COPY.backHref }"
    >
      <template #aside>
        <FaqSearch :query="q" :category="category" />
      </template>
    </UiPageHeader>

    <UiSideTabLayout>
      <template #sidebar>
        <!-- The whole list, not the filtered one: a filter that hides the way
             back to the other topics is a dead end. -->
        <FaqCategoryTabs
          :items="FAQ_PAGE_ITEMS"
          :active="category"
          :query="q"
        />
        <UiSupportCard />
      </template>

      <FaqBoard :key="boardKey" :items="shown">
        <template #empty>
          <template v-if="term">
            {{ FAQ_PAGE_COPY.emptySearch.replace("%s", q ?? "") }}
            <NuxtLink
              :to="clearHref"
              class="focus-visible:ring-gold text-white underline decoration-from-font underline-offset-4 transition-colors hover:text-white/70 focus-visible:ring-2 focus-visible:outline-none"
            >{{ FAQ_PAGE_COPY.searchClear }}</NuxtLink>
          </template>
          <template v-else>{{ FAQ_PAGE_COPY.empty }}</template>
        </template>
      </FaqBoard>
    </UiSideTabLayout>
  </main>
</template>
