// app/components/news/FeaturedBand.vue
<script setup lang="ts">
import { getFeaturedNews } from "~/lib/api/client"

/**
 * Fetches the featured stories and hands them to the band.
 *
 * A thin shell so the call to `getFeaturedNews` runs during SSR and reaches the
 * client through the payload rather than as a second request — the same split
 * `Stats` uses for the wheel (RULES §5/§8).
 */
const { data: stories } = await useAsyncData(
  "news-featured",
  () => getFeaturedNews(),
  { default: () => [] },
)
</script>

<template>
  <NewsFeaturedStories :stories="stories" />
</template>

// src/components/news/FeaturedBand.tsx
import { FeaturedStories } from "@/components/news/FeaturedStories"
import { getFeaturedNews } from "@/lib/api/client"

/**
 * Fetches the featured stories and hands them to the band.
 *
 * A server shell around a Client Component, so the call to `getFeaturedNews`
 * stays on the server and the client bundle carries the carousel's behaviour
 * rather than the API client (RULES §5/§8). The same split `Stats` uses for the
 * wheel.
 */
export async function FeaturedBand() {
  const stories = await getFeaturedNews()

  return <FeaturedStories stories={stories} />
}
